FROM apache/airflow:latest


USER root

RUN apt-get update && \
    apt-get install -y git && \
    apt-get install -y --no-install-recommends vim && \
    apt-get autoremove -yqq --purge && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

USER airflow

COPY requirements.txt /requirements.txt

RUN pip install --no-cache-dir psycopg2-binary requests pandas python-dotenv